#!/usr/bin/env python3
"""Run sq-tool straight from a checkout: ./sq-tool --help"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))

from sqtool.cli import main  # noqa: E402

sys.exit(main())
